spring:
  datasource:
    url: jdbc:oracle:thin:@10.11.39.215:1521:HCS1
    username: h20184501
    password: oraclemaster
    driver-class-name: oracle.jdbc.driver.OracleDriver  
    tomcat:
      max-active: 20
      min-idle: 10